spring.application.name=IslyNews

spring.datasource.url=jdbc:mysql://localhost:3306/IslyNews?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8082

server.servlet.context-path=/

spring.output.ansi.enabled=ALWAYS

# Hugging Face API pour UC3 - Résumer un article (IA)
huggingface.api.key=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